add medellin tweet aqi
gaguevaras/slashbot pull request #6
Opened 2017-05-07 22:11 UTC by Shinkei

no se donde habia que agregar la parte de who para que twitee con mi cuenta, por ahora que twitee con la de Gustavo 😄 @gaguevaras

2017-05-08 12:57 UTC, gaguevaras requested changes
Falta un pedazo, pero estás muy cerca!

2017-05-08 12:57 UTC, gaguevaras commented on classes/Slashbot.class.js
> +        	if (city === 'medellin') {
La API de aqicn solamente acepta `medellín`, creo que tienen un problema de codificación.

2017-05-08 12:57 UTC, gaguevaras commented on classes/Slashbot.class.js
> +        	}
Para usar tus propias credenciales, revisa el contenido de la función `_tweet` para encontrar `getTwitterCredentials`. Ahí ves donde tienes que meter los creds.

2017-05-09 20:49 UTC, Shinkei commented
Twitter no me deja agregar un numero de celular :S y si eso no puedo ver las opciones de desarrollo y la llave que necesito poner en la base de datos, ya de todas formas puse la tilde en medellin

2017-06-10 01:33 UTC, gaguevaras approved these changes

2017-06-10 01:34 UTC, merged